apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-gpu-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    gitops.ownedBy: default
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/manifests/operators/nvidia-gpu-operator/aggregate/overlays/default
    repoURL: https://github.com/na-launch/gpu-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true