apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nfd-worker-nodefeature-write-access
subjects:
  - kind: ServiceAccount
    name: nfd-worker
    namespace: openshift-nfd
roleRef:
  kind: ClusterRole
  name: nfd-nodefeature-writer
  apiGroup: rbac.authorization.k8s.io