apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nfd-master-nodefeature-access
subjects:
  - kind: ServiceAccount
    name: nfd-master
    namespace: openshift-nfd
roleRef:
  kind: ClusterRole
  name: nfd-master-nodefeature-reader
  apiGroup: rbac.authorization.k8s.io