apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-nfd

resources:
  - node-feature-discovery.yaml

  - cr-nfd-worker-nodefeature-writer.yaml
  - cbr-nfd-worker-nodefeature.yaml
  - cr-nfd-master-nodefeaturerules-reader.yaml
  - cbr-nfd-master-nodefeaturerules.yaml
  - cr-nfd-master-nodefeature-reader.yaml
  - cbr-nfd-master-nodefeature.yaml